# Prompts for GPT-5

## Introduction
This script contains a set of prompts designed to evaluate different aspects of GPT-5's capabilities.

## Usage
- The user can input various queries into the model.
- The model will generate responses based on these prompts.

## GOAL
Our goal is to evaluate and enhance the performance of GPT-5 over a 6-month period, focusing on key improvements and user feedback.

## Evaluation Criteria
1. Clarity of Responses
2. Relevance to User Queries
3. Creativity
4. User Satisfaction

## Process
- Collect initial user feedback.
- Analyze the responses generated by the model.
- Based on feedback, iterate on prompts to refine the model’s performance.

## Conclusion
By focusing on the above aspects, we aim to continually improve GPT-5’s interactions and overall user experience. The prompts should be adjusted monthly based on feedback and performance data.


# Update to Prompts
1. Collected various prompts based on recent trends and topics.
2. Ordered them by ML ranking.
3. Further optimized prompts for clarity and engagement.